# Generated by Django 2.0 on 2018-06-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0002_auto_20180614_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='principal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='College Principal'),
        ),
    ]
