# Generated by Django 2.0 on 2018-06-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0003_auto_20180614_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='founded',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
